import {
  MODEL, K_GRID, PATTERNS, PATTERN_LABELS, LOADS, DEFAULT_K,
  greenBudget, intersectionCapacity, lambdasFor, directionalAsymmetry,
} from '../model/constants.js';

/** The mathematical model, written out with the values the program actually uses. */
export default function MathAnalysisPanel() {
  const G = greenBudget();
  const capacity = intersectionCapacity();

  return (
    <div className="math-panel">
      <h3 className="section-title">Mathematical Model</h3>

      <MathSection title="1. Fixed parameters">
        <table className="ia-table">
          <thead><tr><th>Symbol</th><th>Meaning</th><th>Value</th></tr></thead>
          <tbody>
            <tr><td>T</td><td>Arrival horizon</td><td>{MODEL.arrivalHorizon} s</td></tr>
            <tr><td>Δt</td><td>Simulation time step</td><td>{MODEL.dt} s</td></tr>
            <tr><td>C</td><td>Cycle length</td><td>{MODEL.cycleLength} s</td></tr>
            <tr><td>y</td><td>Yellow after every green</td><td>{MODEL.yellow} s</td></tr>
            <tr><td>r</td><td>All-red after every yellow</td><td>{MODEL.allRed} s</td></tr>
            <tr><td>μ</td><td>Service rate while green</td><td>{MODEL.mu} veh/s</td></tr>
            <tr><td>g<sub>min</sub></td><td>Minimum green</td><td>{MODEL.minGreen} s</td></tr>
            <tr><td>g<sub>max</sub></td><td>Maximum green</td><td>{MODEL.maxGreen} s</td></tr>
            <tr><td>G</td><td>Green budget C − 4(y + r)</td><td>{G} s</td></tr>
          </tbody>
        </table>
        <p>
          Phases run in the order N, S, E, W. Only one road holds green at a time, and every green is
          followed by its yellow and its all-red, which is where the 4(y + r) = {4 * (MODEL.yellow + MODEL.allRed)} s
          of lost time per cycle comes from.
        </p>
      </MathSection>

      <MathSection title="2. Poisson arrivals and exponential gaps">
        <p>Arrivals on road i form a Poisson process of rate λ<sub>i</sub>:</p>
        <MathBlock>P(X = k) = e^(−λt) (λt)^k / k!</MathBlock>
        <p>so the gaps between consecutive arrivals are exponential and are generated by inverse CDF:</p>
        <MathBlock>A_i = −ln(1 − U) / λ_i,  U ~ Uniform[0, 1)</MathBlock>
        <p>Arrival times accumulate until t ≤ T; after T no new vehicles appear.</p>
      </MathSection>

      <MathSection title="3. Seeded random numbers">
        <p>Uniform variates come from a 32-bit linear congruential generator:</p>
        <MathBlock>state = (1664525 × state + 1013904223) mod 2^32</MathBlock>
        <MathBlock>U = state / 2^32</MathBlock>
        <p>
          A zero seed is replaced by 1. Each road gets its own stream by XOR-ing the trial seed with a
          fixed offset (N: 0x1A2B3C, S: 0x4D5E6F, E: 0x7A8B9C, W: 0xDEADBE), and trial j of a scenario
          uses seed = seedBase + 31337j. The same seed therefore always produces exactly the same
          arrival arrays, and those arrays are handed unchanged to both systems.
        </p>
      </MathSection>

      <MathSection title="4. Queue evolution">
        <MathBlock>Q_i(t + Δt) = max(0, Q_i(t) + A_i(t) − D_i(t))</MathBlock>
        <p>Departures use a deterministic fractional service accumulator rather than random rounding:</p>
        <MathBlock>serviceCredit_i += μΔt</MathBlock>
        <MathBlock>D_i = min(Q_i, floor(serviceCredit_i))   (green only)</MathBlock>
        <p>
          The credit is reset when the road loses green or when its queue empties. The signals keep
          cycling after T until every queue is empty, so each completed trial satisfies
          total served = total arrivals.
        </p>
      </MathSection>

      <MathSection title="5. Waiting time and fairness">
        <p>The queue area is integrated numerically,</p>
        <MathBlock>queueArea_i = Σ Q_i(t) Δt</MathBlock>
        <p>and the headline metric is the vehicle-weighted mean waiting time</p>
        <MathBlock>W = ( Σ_i queueArea_i ) / ( Σ_i N_i )</MathBlock>
        <p>
          This is total vehicle-seconds of delay per vehicle. It is deliberately not the average of the
          four road means W<sub>i</sub>, because a lightly used road would otherwise count as much as a
          heavily used one. Fairness is the population standard deviation of those four road means:
        </p>
        <MathBlock>F = sqrt[ (1/4) Σ_i (W_i − mean(W_i))² ]</MathBlock>
        <p>A larger F means waiting times are less equal between the roads.</p>
      </MathSection>

      <MathSection title="6. The two systems">
        <p><strong>Equal-Time System</strong> — every road, every cycle:</p>
        <MathBlock>g_i = G / 4 = {G / 4} s</MathBlock>
        <p>
          <strong>Optimized System</strong> — the adaptive queue-weighted policy. At the start of every
          complete cycle it measures the four queues and computes
        </p>
        <MathBlock>w_i = Q_i + k λ_i</MathBlock>
        <MathBlock>g_i = g_min + [ w_i / Σ_j w_j ] (G − 4 g_min)</MathBlock>
        <p>
          k is measured in seconds, so kλ<sub>i</sub> is the number of vehicles expected to arrive on
          road i during the next k seconds: the weight blends the queue that already exists with the
          demand that is about to arrive. The allocation is applied iteratively — every road first
          receives g<sub>min</sub>, the remaining {G - 4 * MODEL.minGreen} s is shared in proportion to
          the weights, any road that would exceed g<sub>max</sub> is fixed at g<sub>max</sub> and its
          spare budget is redistributed among the uncapped roads, repeating until the budget is spent.
          Clamping and then rescaling all four values is not used, because rescaling can push a clamped
          value back outside the bounds. If every weight is zero the split is equal.
        </p>
        <MathBlock>{MODEL.minGreen} ≤ g_i ≤ {MODEL.maxGreen},  Σ_i g_i = {G}</MathBlock>
      </MathSection>

      <MathSection title="7. Traffic scenarios">
        <MathBlock>capacity = μG / C = {capacity.toFixed(7)} veh/s</MathBlock>
        <MathBlock>total λ = ρ × capacity</MathBlock>
        <MathBlock>A = sqrt[ (1/4) Σ_i (λ_i − mean λ)² ] / mean λ</MathBlock>
        <div className="table-scroll">
          <table className="ia-table">
            <thead>
              <tr>
                <th>Pattern</th><th>Shares (N, S, E, W)</th><th>A</th>
                {LOADS.map(rho => <th key={rho}>Σλ at ρ = {rho.toFixed(2)}</th>)}
              </tr>
            </thead>
            <tbody>
              {Object.entries(PATTERNS).map(([name, shares]) => (
                <tr key={name}>
                  <td>{PATTERN_LABELS[name]}</td>
                  <td className="mono">{shares.map(s => s.toFixed(2)).join(', ')}</td>
                  <td>{directionalAsymmetry(lambdasFor(name, LOADS[0])).toFixed(3)}</td>
                  {LOADS.map(rho => (
                    <td key={rho}>{(rho * capacity).toFixed(4)} veh/s</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </MathSection>

      <MathSection title="8. Paired trials and confidence intervals">
        <p>For each paired trial j the arrivals are generated once and given to both systems, then</p>
        <MathBlock>d_j = W_(E,j) − W_(O,j)</MathBlock>
        <MathBlock>r_j = 100 (W_(E,j) − W_(O,j)) / W_(E,j)</MathBlock>
        <p>Over n trials, with the sample standard deviation s<sub>d</sub>,</p>
        <MathBlock>mean d = Σ d_j / n</MathBlock>
        <MathBlock>s_d = sqrt[ Σ (d_j − mean d)² / (n − 1) ]</MathBlock>
        <MathBlock>CI₉₅ = mean d ± t_(0.975, n−1) · s_d / sqrt(n)</MathBlock>
        <p>
          The critical value is the Student t value for n − 1 degrees of freedom, obtained from the t
          distribution itself rather than from the 1.96 normal approximation. The same construction is
          applied to the n individual percentage reductions r<sub>j</sub>, and the two-sided paired
          t-test p-value comes from the same distribution.
        </p>
      </MathSection>

      <MathSection title="9. Calibrating k">
        <p>k is chosen on separate training scenarios (ρ = 0.75 only, and seed bases disjoint from the evaluation seeds) by minimising</p>
        <MathBlock>J(k) = 0.7·mean(W_O/W_E) + 0.2·mean(Qmax_O/Qmax_E) + 0.1·mean(F_O/F_E)</MathBlock>
        <p>
          Each ratio is formed from the mean performance of a training scenario, and the three scenario
          ratios are then averaged. Because every component is a ratio of like quantities the units
          cancel, so the three terms can legitimately be added. The tested grid is
          {' '}{K_GRID.join(', ')} seconds, and the reported k is whichever value actually minimises the
          computed J — the default of {DEFAULT_K} s is only a starting point that the calibration mode
          confirms or overrides.
        </p>
      </MathSection>

      <MathSection title="10. Assumptions and limitations">
        <div className="assumption-grid">
          <div>
            <strong>Assumptions</strong>
            <ul>
              <li>Arrivals are Poisson: independent, memoryless, constant rate</li>
              <li>All vehicles are identical and occupy no physical length</li>
              <li>Service rate μ is constant for the whole of a green phase</li>
              <li>No turning movements, lane choice or lane blocking</li>
              <li>Queue storage is unlimited</li>
              <li>Driver reaction and start-up loss are absorbed into μ</li>
              <li>No pedestrian phases, buses or emergency vehicles</li>
            </ul>
          </div>
          <div>
            <strong>Limitations</strong>
            <ul>
              <li>Real arrival rates vary through the day; λ here is constant</li>
              <li>Real traffic arrives in platoons released by upstream signals, which breaks independence</li>
              <li>The policy sees the queue exactly; real detectors are noisy</li>
              <li>Delay is measured as queue area, not per-vehicle door-to-door travel time</li>
              <li>The percentage reductions apply to this model, not to any specific real junction</li>
            </ul>
          </div>
        </div>
        <p className="note">
          This is a simplified educational simulation written for an IB Mathematics: Applications and
          Interpretation HL Internal Assessment. It is not a traffic-engineering control system, and a
          real intersection would not necessarily achieve the reductions reported here.
        </p>
      </MathSection>
    </div>
  );
}

function MathSection({ title, children }) {
  return (
    <div className="math-section">
      <div className="math-section-title">{title}</div>
      <div className="math-section-body">{children}</div>
    </div>
  );
}

function MathBlock({ children }) {
  return <div className="math-block"><code>{children}</code></div>;
}
